"""Initial structure

Revision ID: 01
Revises: 
Create Date: 2026-02-20 11:46:29.136329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '01'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_requests',
    sa.Column('correlation_id', sa.String(), nullable=False),
    sa.Column('source', sa.Enum('telegram', name='webhook_source_enum'), server_default='telegram', nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'success', 'failed', name='webhook_request_status_enum'), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_requests_correlation_id'), 'webhook_requests', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_webhook_requests_created_at'), 'webhook_requests', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_requests_created_at'), table_name='webhook_requests')
    op.drop_index(op.f('ix_webhook_requests_correlation_id'), table_name='webhook_requests')
    op.drop_table('webhook_requests')
    op.execute("DROP TYPE webhook_source_enum")
    op.execute("DROP TYPE webhook_request_status_enum")
    # ### end Alembic commands ###
